openapi: 3.0.0
x-stoplight:
  id: 2ebhzpp6a9rxu
info:
  title: is.ifsf.h2h.rest.listener.doc
  version: 0.0.1
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/clients/{clientID}/events/{correlationID}/paymentRequests':
    post:
      summary: Send a Payment request
      operationId: post-user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
              examples: {}
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aaa:
                  $ref: '#/components/schemas/PaymentRequest'
            examples: {}
        description: Post the necessary fields for the API to create a new user.
      description: POST to process a payment request (Post-Pay)
    parameters:
      - schema:
          type: string
        name: clientID
        in: path
        required: true
        description: '<= 40 characters Client ID is assigned by ICAD Sistemi to each client, and is agreed before communications is possible. This ID is not used for business processing purposes and can be chosen arbitrarily, but could be a merchant ID or terminal ID or other suitable identifier that is already available.'
      - schema:
          type: string
        name: correlationID
        in: path
        required: true
        description: '[ 1 .. 40 ] characters Correlation ID is a mandatory unique identifier assigned by the client to each customer transaction, which in this context means a group of related messages linked to a single customer event, such as an authorisation and a subsequent reversal. This specification does not define how the correlation ID is derived, because suitable method is dependent on the design of the client and source of transactions. Possibilities could be a sequentially incrementing counter (similar to STAN found in ISO 8583 interfaces), a combination of individual fields (e.g. terminal ID and reliable timestamp) or a GUID'
components:
  schemas:
    Card:
      title: Card
      x-stoplight:
        id: z4mxoz7ptpwiv
      type: object
      properties:
        cardISOType:
          type: string
          x-stoplight:
            id: 45ooj00snwhs2
          description: |
            This is highly dependent on the rules set by the Card Brands. Currently the first 6 digits can be displayed.
        context:
          type: string
          x-stoplight:
            id: ezo90i3szram7
          enum:
            - token
            - MSR
            - ICC
            - CNP
            - NFC
          description: Context identifies the different use cases related to cards.
        encryptedSensitiveCardDetailsReq:
          type: string
          x-stoplight:
            id: yy89joe66vms1
          description: |-
            The JWE data type used to transmit a key. Use base 58 encoding.
            The JWE content is defined in the official documentation under the voice POST/sensitiveCardDetailsReq

            An example is:

            {
              "context": "MSR",
              "track2": "stringst",
              "expiry": {
                "month": 1,
                "year": 1500
              },
              "PAN": "string"
            }
        issuerNumber:
          type: string
          x-stoplight:
            id: xkskvimjkuiyj
          description: |
            Card Issue Number is the card issuer number (also known as card sequence number) if available and applicable to the card type.
        maskedPAN:
          type: string
          x-stoplight:
            id: sfje06z199q4k
          description: |
            Masked Primary Account Number is not present in requests
        maskingType:
          type: string
          x-stoplight:
            id: 0net2beno46ye
          description: |
            Masking type consistent with DE-127-1.34. Specified which digits are masked (bitmap: 0 clear - 1 masked)
        pinData:
          type: string
          x-stoplight:
            id: mf6yrjk23q0j2
      required:
        - cardISOType
        - context
        - encryptedSensitiveCardDetailsReq
        - issuerNumber
        - maskedPAN
        - maskingType
        - pinData
    Merchant:
      title: Merchant
      x-stoplight:
        id: n80pa5afmaqp3
      type: object
      properties:
        country:
          type: string
          x-stoplight:
            id: 75j280syc18oq
          description: |
            ISO-3166 / UN/ECE REC 09 Codes
        categoryNumber:
          type: string
          x-stoplight:
            id: ljcozl76c4hxm
          description: |
            category number is the ISO merchant category code appropriate for the merchant
        merchantID:
          type: string
          x-stoplight:
            id: kes68kpxmegob
          description: |-
            40 character description.

            The only mandatory field, used to identify the fuel station
        name:
          type: string
          x-stoplight:
            id: ve3cun819j3b9
          description: |
            40 character description.
        networkID:
          type: string
          x-stoplight:
            id: 27wh3b1dxmbur
          description: |
            16 character description.
      required:
        - merchantID
    PaymentContext:
      title: PaymentContext
      x-stoplight:
        id: 30048z049p2h2
      type: object
      properties:
        context:
          type: string
          x-stoplight:
            id: j7sazmhwingk5
          enum:
            - token
            - ICC
            - MSR
            - NFC
            - CNP
          description: Context identifies the different use cases related to cards.
        cardReadMethod:
          type: string
          x-stoplight:
            id: or8d4t5ur0bw9
          enum:
            - MAGSTRIPE
            - CONTACLESS_MAGSTRIPE
          description: |
            Card Read Method indicates how the card details were read at the POI
        cardholderAuthEntity:
          type: string
          x-stoplight:
            id: fsqe3vfhuaeam
          enum:
            - AUTHORISER
            - TERMINAL
            - MERCHANT
          description: |
            Cardholder Authentication Entity indicates the party who has authenticated the cardholder. Omitted if cardholder authentication has not been performed at the time the message is created
        cardholderAuthMethod:
          type: string
          x-stoplight:
            id: al64l582ddtxg
          enum:
            - PIN_OFFLINE_CLEAR
            - PIN_ONLINE
            - SIGNATURE
          description: |
            Cardholder Authentication Method indicates how the method by which cardholder has been authenticated, if known
        cardholderPresent:
          type: string
          x-stoplight:
            id: brz6dvgobc9ks
          description: |
            Cardholder Present if the cardholder is present at the POI at the time of transaction
          enum:
            - PRESENT
        fallback:
          type: string
          x-stoplight:
            id: rq3tlemfszdem
          enum:
            - 'yes'
            - 'no'
        fleetEntryMethod:
          type: string
          x-stoplight:
            id: so9pddfgbgy7j
          description: |
            Fleet Entry Method indicates how fleet data was entered at the POI, if known and applicable
      required:
        - context
        - cardReadMethod
        - cardholderAuthEntity
        - cardholderAuthMethod
        - cardholderPresent
        - fallback
    PaymentRequest:
      title: PaymentRequest
      x-stoplight:
        id: d9a407640a5c3
      type: object
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        card:
          $ref: '#/components/schemas/Card'
        paymentContext:
          $ref: '#/components/schemas/PaymentContext'
        encryptedCustomerData:
          type: string
          x-stoplight:
            id: 8go5c6tfpbrty
        merchant:
          $ref: '#/components/schemas/Merchant'
        POI:
          $ref: '#/components/schemas/POI'
        saleContext:
          type: string
          x-stoplight:
            id: cwwdhkygntk0w
          description: |
            16 character description.
        transaction:
          $ref: '#/components/schemas/Transaction'
      required:
        - card
        - paymentContext
        - encryptedCustomerData
        - merchant
        - POI
        - saleContext
        - transaction
    POI:
      title: POI
      x-stoplight:
        id: faud6p8k2wh36
      type: object
      properties:
        siteID:
          type: string
          x-stoplight:
            id: li945ajve5nd1
          description: |
            40 character ID
        address:
          type: string
          x-stoplight:
            id: q0sozvamdjkh9
          description: |
            Point of interaction address
        POIType:
          type: string
          x-stoplight:
            id: 0y4e3l5r2uzth
          description: |
            Types of points of interaction
        POIID:
          type: string
          x-stoplight:
            id: saywfxyq9c11e
          description: 'The only mandatory field, it''s the terminal ID'
        language:
          type: string
          x-stoplight:
            id: 63jls41xxfni0
          description: 'ISO 639 language code, not used'
        readerCapabilities:
          type: object
          x-stoplight:
            id: 53w7qet7i303x
          description: 'This is the schema used to define the capabilities, not used'
          properties:
            cardCapture:
              type: string
              x-stoplight:
                id: w8nl547sq4f8y
              enum:
                - 'yes'
                - 'no'
            cardReading:
              type: string
              x-stoplight:
                id: py89xtnbkfbpq
              description: |
                Card Reading Capability indicates the means of card data entry to the POI. Omitted if unknown
              enum:
                - BARCODE
                - CONTACTLESS_ENV
                - CONTACTLESS_MAGSTRIPE
                - EMV
                - KEY_ENTRY
                - MAGSTRIPE
                - NONE
            cardWriting:
              type: string
              x-stoplight:
                id: 471qtxfw07v7e
              description: |
                Card Writing Capability indicates the means of card data entry to the POI. Omitted if unknown
              enum:
                - EMV
                - MAGSTRIPE
                - NONE
            cardholderVerification:
              type: string
              x-stoplight:
                id: x1y27zbysx4pq
              enum:
                - CDCVM
                - NO_CVM
                - PIN_OFFLINE_CLEAR
                - PIN_OFFLINE_ENCRYPTED
                - PIN_ONLINE
                - SIGNATURE
              description: |
                Card Verification Capability indicates the means of cardholder verification at the POI. Omitted if unknown
            environment:
              type: string
              x-stoplight:
                id: ztkqhra5m8gyb
              enum:
                - MERCHANT_ATTENDED
                - MERCHANT_UNATTENDED
                - CARDHOLDER
              description: |
                Environment indicates the characteristics of the POI. Omitted if unknown
            pinLength:
              type: integer
              x-stoplight:
                id: xqdsqqomyravc
              description: |
                PIN Length indicates the maximum length of PIN supported by the card terminal. Omit this field entirely if the PIN entry length is unknown of the POI does not support PIN entry at all
            cashierDisplayCapabilities:
              type: integer
              x-stoplight:
                id: eu7lxqe68mb17
            cardholderDisplayCapabilities:
              type: integer
              x-stoplight:
                id: h5d195bww2h0r
            cashierPrintCapabilities:
              type: integer
              x-stoplight:
                id: 4fepwbbjllv7w
            cardholderPrintCapabilities:
              type: integer
              x-stoplight:
                id: 86wu35n5lfrey
        POITraceNumber:
          type: string
          x-stoplight:
            id: ll2ux3lexve8h
      required:
        - POIID
    Transaction:
      title: Transaction
      x-stoplight:
        id: d1spy52xf60vf
      type: object
      properties:
        currency:
          type: string
          x-stoplight:
            id: hv6ul2r6rgz3s
          description: |
            ISO-4217 / UN/ECE REC 09 Codes
        transactionAmount:
          type: string
          x-stoplight:
            id: xhpyajccg3wxy
          description: |
            16,5 decimal value
        batchNumber:
          type: string
          x-stoplight:
            id: z92q3hhm9jqd9
          description: |
            Batch Number indicates the reconciliation batch to which this transaction is assigned. The batch number is assigned by the API client.
        dateTimeLocal:
          type: string
          x-stoplight:
            id: prih5emzqnxbv
        transactionLines:
          type: array
          x-stoplight:
            id: 1bn9dyatj8dwy
          description: |
            List of the article(s) purchased in this transaction.
          items:
            $ref: '#/components/schemas/TransactionLine'
        serviceLevel:
          type: string
          x-stoplight:
            id: gxa9ga6gcvf5a
          enum:
            - FULL
            - SELF
            - INTERNET
          description: |
            Indicates the service rendered at the site, if known and applicable
        transctionID:
          type: string
          x-stoplight:
            id: cktdlqj7hin6u
          description: |
            Unique Message Transaction Identifier
        traceNumber:
          type: integer
          x-stoplight:
            id: oet645xruuf3b
          description: |
            Trace Number is an API client assigned transaction number. This should be a sequentially incrementing number that is unique to each new message sent.
      required:
        - transactionAmount
        - batchNumber
        - dateTimeLocal
        - transactionLines
        - transctionID
        - traceNumber
    TransactionLine:
      title: TransactionLine
      x-stoplight:
        id: jjeeikyfnulla
      type: object
      properties:
        trxLineSequenceNumber:
          type: integer
          x-stoplight:
            id: 47isr5vh96h1e
          description: |
            8 digit numeric value
        productCode:
          type: integer
          x-stoplight:
            id: rsmzw5poies4n
          description: |-
            3 digit numeric value

            0 stands for OIL articles, 1 stands for NON OIL articles
        productDescription:
          type: string
          x-stoplight:
            id: afft60iqcy8xl
          description: |
            40 character description.
        additionalProductCode:
          type: object
          x-stoplight:
            id: 5jh1k9bfnn0or
          required:
            - posCodeType
          properties:
            posCodeFormat:
              type: string
              x-stoplight:
                id: gbwjq5l3t08xk
            posCodeType:
              type: string
              x-stoplight:
                id: wurlnui7t4x4f
              description: 'Article code, <= 14 characters'
        refillingPointID:
          type: string
          x-stoplight:
            id: 4l8sk16xt3mpr
        pumpLinked:
          type: string
          x-stoplight:
            id: fb1vem75xs4lt
        unitPrice:
          type: number
          x-stoplight:
            id: zxl2ssyo3js64
          description: |
            16,5 decimal value
        salesQuantity:
          type: object
          x-stoplight:
            id: u4q6t98bgttdp
          required:
            - value
          properties:
            value:
              type: number
              x-stoplight:
                id: 3ata88uv6m1g0
              description: |
                12,5 decimal value
            uom:
              type: string
              x-stoplight:
                id: 9jjn9k7rkcc13
        salesAmount:
          type: number
          x-stoplight:
            id: tnmxuvxl08cmb
          description: |
            16,5 decimal value
        taxCode:
          type: string
          x-stoplight:
            id: p6xbe6ums5dgq
          description: 'tax code applied to the product, <= 1 characters'
        taxAmount:
          type: number
          x-stoplight:
            id: dnh4wt4qg78zd
          description: |
            16,5 decimal value
      required:
        - trxLineSequenceNumber
        - productCode
        - additionalProductCode
        - unitPrice
        - salesQuantity
        - salesAmount
  securitySchemes:
    API Key - 1:
      type: oauth2
